c
c Copyright (c) 1996-2004 by Gennady Serdyuk.  All rights reserved.
c gserdyuk@mail.ru
c 
c Released under GPL v 2.0
c



      SUBROUTINE DECODE(U,NOHAR,ISIZE_MAXNODE)
C
C  נ/נ נEPECשלKי üלEMEHOB BEKTOPA-PEûEHיס BHץTPי CAMOחO
C  BEKTOPA-PEûEHיס הלס נPיBEהEHיס HץMEPAדיי ץתלOB
C  B COOTBETCTBיE C יCXOהHOך HץMEPAדיEך.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/KOLNAL/KOL,NAL
      COMMON/NOUZL /NOUZ,INOUZ1

      LOGICAL NAL(4)
      INTEGER ISIZE_MAXNODE
      INTEGER KOL(4),NTOT,NOUZ(100),INOUZ(100),TERM
      DOUBLE COMPLEX S,U(1),UT(ISIZE_MAXNODE)

C  Oג‎EE KOל-BO ץתלOB:
      NTOT=KOL(1)+KOL(2)+KOL(3)
C     WRITE(6, 810) (IVA,NOUZ(IVA),IVA=1,NTOT)
C 810 FORMAT(2X,'DECODE: NOUZ(',I3,')=',I4)
C     WRITE(6, 815) NTOT
C 815 FORMAT(2X,'NTOT=',I5)

C  BO BCEX ץתלAX
      DO 10 I=1,NTOT
C  נPOBEהEM נEPECשלKץ ית  U  B UT   B COOTBETCTBיי C
C  BEKTOPOM OTOגPAצEHיס  NOUZ    /CM. נ/נ SORTUZ/
      TERM=NOUZ(I)
   10 UT(TERM)=U(I)
C  TEנEPר נEPEניûEM ית CץצEגHOחO BEKTOPA UT
C  B BEKTOP PEûEHיס U:
      DO 15 I=1,NTOT
C     WRITE(6, 14) I,UT(I)
C  14 FORMAT(2X,'DECODE: U(',I3,')=',E12.5,2X,E12.5)
   15 U(I)=UT(I)
      RETURN
C     DEBUG SUBTRACE,SUBCHK,INIT(I,TERM)
      END
